# -*- coding: utf-8 -*-
"""LR_4_task_2_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-nzWJEN1mpzjDJEgPptweCD7lPqoL_kB
"""

import numpy as np
from sklearn import linear_model
import sklearn.metrics as sm
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

def plot_learning_curves(model, X, y, ax):
    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=0.2
    )

    train_errors, val_errors = [], []

    for m in range(1, len(X_train)):
        model.fit(X_train[:m], y_train[:m])
        y_train_pred = model.predict(X_train[:m])
        y_val_pred = model.predict(X_val)

        train_errors.append(
            mean_squared_error(y_train[:m], y_train_pred)
        )
        val_errors.append(
            mean_squared_error(y_val, y_val_pred)
        )

    ax.plot(np.sqrt(train_errors), "r-+", linewidth=2, label="Train RMSE")
    ax.plot(np.sqrt(val_errors), "b-", linewidth=3, label="Validation RMSE")
    ax.set_xlabel("Training set size")
    ax.set_ylabel("RMSE")
    ax.legend()


m = 100
X = 6 * np.random.rand(m, 1) - 5
y = 0.5 * X**2 + X + 2 + np.random.randn(m, 1)

regr = linear_model.LinearRegression()

poly10 = Pipeline([
    ("poly_features", PolynomialFeatures(degree=10, include_bias=False)),
    ("lin_reg", linear_model.LinearRegression()),
])

poly2 = Pipeline([
    ("poly_features", PolynomialFeatures(degree=2, include_bias=False)),
    ("lin_reg", linear_model.LinearRegression()),
])

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

plot_learning_curves(regr, X, y, axes[0])
axes[0].set_title("Linear Regression")

plot_learning_curves(poly10, X, y, axes[1])
axes[1].set_title("Polynomial Regression (degree=10)")

plot_learning_curves(poly2, X, y, axes[2])
axes[2].set_title("Polynomial Regression (degree=2)")

plt.tight_layout()
plt.show()