# -*- coding: utf-8 -*-
"""LR_4_task_2_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pVDFn3Ft1pkob2e-NhSayMyT_jSSjF3P
"""

import numpy as np
from sklearn import linear_model
import sklearn.metrics as sm
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt

m = 100
X = 6 * np.random.rand(m, 1) - 5
y = 0.5 * X ** 2 + X + 2 + np.random.randn(m, 1)

plt.scatter(X, y, color='green', label='Дані')
plt.xlabel('X')
plt.ylabel('y')
plt.title('Випадкові дані')
plt.legend()
plt.show()

regr = linear_model.LinearRegression()
regr.fit(X, y)
ypred = regr.predict(X)

plt.scatter(X, y, color='green', label='Дані')
plt.plot(X, ypred, color='blue', linewidth=3, label='Лінійна регресія')
plt.xlabel('X')
plt.ylabel('y')
plt.title('Лінійна регресія')
plt.legend()
plt.show()

poly_features = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly_features.fit_transform(X)
poly_regr = linear_model.LinearRegression()
poly_regr.fit(X_poly, y)
poly_ypred = poly_regr.predict(X_poly)

plt.scatter(X, y, color='green', label='Дані')
plt.plot(np.sort(X, axis=0),
poly_regr.predict(poly_features.transform(np.sort(X, axis=0))),
color='red', linewidth=3, label='Поліноміальна регресія')
plt.xlabel('X')
plt.ylabel('y')
plt.title('Поліноміальна регресія')
plt.legend()
plt.show()


print("X[0]:", X[0])
print("X_poly[0]:", X_poly[0])

mse_linear = sm.mean_squared_error(y, ypred)
r2_linear = sm.r2_score(y, ypred)
mae_linear = sm.mean_absolute_error(y, ypred)
print("Лінійна регресія:")
print("Mean Squared Error (MSE):", round(mse_linear, 2))
print("R2 score:", round(r2_linear, 2))
print("Mean Absolute Error (MAE):", round(mae_linear, 2))

print("Коефіцієнти лінійної регресії:", regr.coef_)
print("bias лінійної регресії:", regr.intercept_)

mse_poly = sm.mean_squared_error(y, poly_ypred)
r2_poly = sm.r2_score(y, poly_ypred)
mae_poly = sm.mean_absolute_error(y, poly_ypred)
print("\nПоліноміальна регресія:")
print("Mean Squared Error (MSE):", round(mse_poly, 2))
print("R2 score:", round(r2_poly, 2))
print("Mean Absolute Error (MAE):", round(mae_poly, 2))

print("Коефіцієнти поліноміальної регресії:", poly_regr.coef_)
print("bias поліноміальної регресії:", poly_regr.intercept_)