# -*- coding: utf-8 -*-
"""LR_2_task_3_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/137s2r3AldZzXdkWhpjLN7HBS7LkEflhA
"""

from sklearn.datasets import load_iris
# Завантажуємо дані, викликавши функцію load_iris:
iris_dataset = load_iris()
# Об'єкт iris, що повертається load_iris, є об'єктом Bunch, який дуже
# схожий на словник. Він містить ключі та значення
print("Ключі iris_dataset: \n{}".format(iris_dataset.keys()))

print("iris_dataset.filename:")
print(iris_dataset.filename + "\n...")

print("iris_dataset.data_module:")
print(iris_dataset.data_module + "\n...")

print("iris_dataset['DESCR'][:193]:")
print(iris_dataset['DESCR'][:193] + "\n...")

print("Назви відповідей: {}".format(iris_dataset['target_names']))

print("Назва ознак: \n{}".format(iris_dataset['feature_names']))

print("Тип масиву data: {}".format(type(iris_dataset['data'])))
print("Форма масиву data: {}".format(iris_dataset['data'].shape))

print("Значення ознак перших п'яти елементів:\n{}".format(iris_dataset["data"][:5]))

print("Тип масиву target: {}".format(type(iris_dataset['target'])))
print("Відповіді:\n{}".format(iris_dataset['target']))