# -*- coding: utf-8 -*-
"""LR_5_task_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D6tR0WaAkGsukavLTyTEODCVALlIIPE0
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.model_selection import train_test_split,  GridSearchCV

def visualize_classifier(classifier, X, y, title):
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1

    xx, yy = np.meshgrid(
        np.arange(x_min, x_max, 0.01),
        np.arange(y_min, y_max, 0.01)
    )

    Z = classifier.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)

    plt.figure()
    plt.contourf(xx, yy, Z, alpha=0.4)
    plt.scatter(X[:, 0], X[:, 1], c=y, edgecolor='black')
    plt.title(title)
    plt.show()

if __name__ == "__main__":
  input_file = 'data_random_forests.txt'
  data = np.loadtxt (input_file, delimiter=',')
  X, y = data[:, :-1], data[:, -1]

  # Розбиття даних на три класи на підставі міток
  class_0 = np.array (X[y==0])
  class_1 = np.array (X[y==1])
  class_2 = np.array (X[y==2])

  # Розбиття даних на навчальний та тестовий набори
  X_train, X_test, y_train, y_test = train_test_split(
      X, y, test_size=0.25, random_state=5)

  # Визначення сітки значень параметрів
  parameter_grid = [ {
      'n_estimators': [100], 'max_depth': [2, 4, 7, 12, 16]
      },
       {
           'max_depth': [4],
           'n_estimators': [25, 50, 100, 250]
                        }
                     ]

  # metrics = ['precision_weighted']
  metrics = ['recall_weighted']

  for metric in metrics:
    print("\n##### Searching optimal parameters for", metric)
    classifier = GridSearchCV(
        ExtraTreesClassifier (random_state=0),
        parameter_grid, cv=5, scoring=metric)
    classifier.fit (X_train, y_train)

    print("\nGrid scores for the parameter grid:")
    means = classifier.cv_results_['mean_test_score']
    params = classifier.cv_results_['params']

    for mean, param in zip(means, params):
        print(param, '-->', round(mean, 3))
    print("\nBest parameters:", classifier.best_params_)

  y_pred = classifier.predict(X_test)
  print("\nPerformance report:\n")
  print (classification_report (y_test, y_pred))