# -*- coding: utf-8 -*-
"""LR_6_task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/163YRd482lceQwz-Ipk8KAP6fuZeoPFL_
"""

import pandas as pd
import numpy as np
from pprint import pprint

# Дані
data = [
    {"Day": "D1", "Outlook": "Sunny", "Humidity": "High", "Wind": "Weak", "Play": "No"},
    {"Day": "D2", "Outlook": "Sunny", "Humidity": "High", "Wind": "Strong", "Play": "No"},
    {"Day": "D3", "Outlook": "Overcast", "Humidity": "High", "Wind": "Weak", "Play": "Yes"},
    {"Day": "D4", "Outlook": "Rain", "Humidity": "High", "Wind": "Weak", "Play": "Yes"},
    {"Day": "D5", "Outlook": "Rain", "Humidity": "Normal", "Wind": "Weak", "Play": "Yes"},
    {"Day": "D6", "Outlook": "Rain", "Humidity": "Normal", "Wind": "Strong", "Play": "No"},
    {"Day": "D7", "Outlook": "Overcast", "Humidity": "Normal", "Wind": "Strong", "Play": "Yes"},
    {"Day": "D8", "Outlook": "Sunny", "Humidity": "High", "Wind": "Weak", "Play": "No"},
    {"Day": "D9", "Outlook": "Sunny", "Humidity": "Normal", "Wind": "Weak", "Play": "Yes"},
    {"Day": "D10", "Outlook": "Rain", "Humidity": "Normal", "Wind": "Weak", "Play": "Yes"},
    {"Day": "D11", "Outlook": "Sunny", "Humidity": "Normal", "Wind": "Strong", "Play": "Yes"},
    {"Day": "D12", "Outlook": "Overcast", "Humidity": "High", "Wind": "Strong", "Play": "Yes"},
    {"Day": "D13", "Outlook": "Overcast", "Humidity": "Normal", "Wind": "Weak", "Play": "Yes"},
    {"Day": "D14", "Outlook": "Rain", "Humidity": "High", "Wind": "Strong", "Play": "No"},
]

df = pd.DataFrame(data)
attributes = ["Outlook", "Humidity", "Wind"]

# --- Функція друку таблиці частот ---
def print_frequency_table(df, attr):
    freq_table = pd.crosstab(df[attr], df["Play"])
    print(f"\n{'='*30}")
    print(f"Frequency Table for {attr}")
    print(f"{'='*30}")
    print(f"{'':<10} {'Yes':>5} {'No':>5}")
    for index, row in freq_table.iterrows():
        yes_count = row.get("Yes", 0)
        no_count = row.get("No", 0)
        print(f"{index:<10} {yes_count:>5} {no_count:>5}")

# --- Функція друку таблиці ймовірностей ---
def print_likelihood_table(df, attr):
    freq_table = pd.crosstab(df[attr], df["Play"])
    total_yes = freq_table["Yes"].sum()
    total_no = freq_table["No"].sum()
    total_all = total_yes + total_no

    print(f"\n{'='*50}")
    print(f"Likelihood Table for {attr}")
    print(f"{'='*50}")
    print(f"{attr:<10} {'Yes':>12} {'No':>12} {'Total':>12}")

    for index, row in freq_table.iterrows():
        yes_count = row.get("Yes", 0)
        no_count = row.get("No", 0)
        total_row = yes_count + no_count

        yes_frac = f"{yes_count}/{total_yes}"
        no_frac = f"{no_count}/{total_no}"
        total_frac = f"{total_row}/{total_all}"

        print(f"{index:<10} {yes_frac:>12} {no_frac:>12} {total_frac:>12}")

    # Підсумки
    print(f"{'Total':<10} {total_yes:>9}/{total_all} {total_no:>9}/{total_all} {total_all:>9}/{total_all}")
    print("\n")

# --- Будуємо таблиці ---
likelihood_tables = {}
for attr in attributes:
    print_frequency_table(df, attr)
    print_likelihood_table(df, attr)

    # Зберігаємо ймовірності
    freq_table = pd.crosstab(df[attr], df["Play"])
    total_yes = freq_table["Yes"].sum()
    total_no = freq_table["No"].sum()
    likelihood_tables[attr] = {
        "Yes": {index: row.get("Yes", 0)/total_yes for index, row in freq_table.iterrows()},
        "No":  {index: row.get("No", 0)/total_no for index, row in freq_table.iterrows()}
    }

# --- Ймовірності класів ---
class_probs = df["Play"].value_counts(normalize=True).to_dict()

def predict_play_step_by_step(new_day, likelihood_tables, class_probs, attributes):
    print(f"\nPredicting for: {new_day}\n")

    P_yes_components = []
    P_no_components = []

    # Крок 1: Ймовірності по атрибутах
    for attr in attributes:
        val = new_day[attr]
        P_attr_yes = likelihood_tables[attr]["Yes"].get(val, 0)
        P_attr_no  = likelihood_tables[attr]["No"].get(val, 0)
        P_yes_components.append(P_attr_yes)
        P_no_components.append(P_attr_no)
        print(f"{attr} = {val} -> P({attr}|Yes) = {P_attr_yes:.4f}, P({attr}|No) = {P_attr_no:.4f}")

    # Крок 2: Добуток ймовірностей
    product_yes = np.prod(P_yes_components)
    product_no  = np.prod(P_no_components)
    print(f"\nProduct of likelihoods: P(Attributes|Yes) = {product_yes:.6f}, P(Attributes|No) = {product_no:.6f}")

    # Крок 3: Множимо на апріорні ймовірності класів
    P_yes = product_yes * class_probs.get("Yes", 0)
    P_no  = product_no  * class_probs.get("No", 0)
    print(f"P(Yes) * P(Yes prior) = {P_yes:.6f}")
    print(f"P(No)  * P(No prior)  = {P_no:.6f}")

    # Крок 4: Нормалізація
    total = P_yes + P_no
    P_yes_norm = P_yes / total
    P_no_norm  = P_no / total
    print(f"\nNormalized probabilities: P(Yes) = {P_yes_norm:.4f}, P(No) = {P_no_norm:.4f}")

    return P_yes_norm, P_no_norm

new_day = {"Outlook": "Rain", "Humidity": "High", "Wind": "Weak"}
P_yes, P_no = predict_play_step_by_step(new_day, likelihood_tables, class_probs, attributes)

new_day = {"Outlook": "Overcast", "Humidity": "High", "Wind": "Weak"}
P_yes, P_no = predict_play_step_by_step(new_day, likelihood_tables, class_probs, attributes)

