# -*- coding: utf-8 -*-
"""LR_6_task_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YwpwEhpfuAGn47zVssbVYV_y6mOz5T7M
"""

import pandas as pd
import numpy as np

# --- Дані ---
data = [
    {"Day": "D1", "Outlook": "Sunny", "Humidity": "High", "Wind": "Weak", "Play": "No"},
    {"Day": "D2", "Outlook": "Sunny", "Humidity": "High", "Wind": "Strong", "Play": "No"},
    {"Day": "D3", "Outlook": "Overcast", "Humidity": "High", "Wind": "Weak", "Play": "Yes"},
    {"Day": "D4", "Outlook": "Rain", "Humidity": "High", "Wind": "Weak", "Play": "Yes"},
    {"Day": "D5", "Outlook": "Rain", "Humidity": "Normal", "Wind": "Weak", "Play": "Yes"},
    {"Day": "D6", "Outlook": "Rain", "Humidity": "Normal", "Wind": "Strong", "Play": "No"},
    {"Day": "D7", "Outlook": "Overcast", "Humidity": "Normal", "Wind": "Strong", "Play": "Yes"},
    {"Day": "D8", "Outlook": "Sunny", "Humidity": "High", "Wind": "Weak", "Play": "No"},
    {"Day": "D9", "Outlook": "Sunny", "Humidity": "Normal", "Wind": "Weak", "Play": "Yes"},
    {"Day": "D10", "Outlook": "Rain", "Humidity": "Normal", "Wind": "Weak", "Play": "Yes"},
    {"Day": "D11", "Outlook": "Sunny", "Humidity": "Normal", "Wind": "Strong", "Play": "Yes"},
    {"Day": "D12", "Outlook": "Overcast", "Humidity": "High", "Wind": "Strong", "Play": "Yes"},
    {"Day": "D13", "Outlook": "Overcast", "Humidity": "Normal", "Wind": "Weak", "Play": "Yes"},
    {"Day": "D14", "Outlook": "Rain", "Humidity": "High", "Wind": "Strong", "Play": "No"},
]

df = pd.DataFrame(data)
attributes = ["Outlook", "Humidity", "Wind"]

# --- Функції друку таблиць ---
def print_frequency_table(df, attr):
    freq_table = pd.crosstab(df[attr], df["Play"])
    print(f"\n{'='*30}")
    print(f"Frequency Table for {attr}")
    print(f"{'='*30}")
    print(f"{'':<10} {'Yes':>5} {'No':>5}")
    for index, row in freq_table.iterrows():
        yes_count = row.get("Yes", 0)
        no_count = row.get("No", 0)
        print(f"{index:<10} {yes_count:>5} {no_count:>5}")

def print_likelihood_table(df, attr):
    freq_table = pd.crosstab(df[attr], df["Play"])
    total_yes = freq_table["Yes"].sum()
    total_no = freq_table["No"].sum()
    total_all = total_yes + total_no

    print(f"\n{'='*50}")
    print(f"Likelihood Table for {attr}")
    print(f"{'='*50}")
    print(f"{attr:<10} {'Yes':>12} {'No':>12} {'Total':>12}")

    for index, row in freq_table.iterrows():
        yes_count = row.get("Yes", 0)
        no_count = row.get("No", 0)
        total_row = yes_count + no_count
        yes_frac = f"{yes_count}/{total_yes}"
        no_frac = f"{no_count}/{total_no}"
        total_frac = f"{total_row}/{total_all}"
        print(f"{index:<10} {yes_frac:>12} {no_frac:>12} {total_frac:>12}")

    print(f"{'Total':<10} {total_yes:>9}/{total_all} {total_no:>9}/{total_all} {total_all:>9}/{total_all}\n")

# --- Будуємо таблиці ---
likelihood_tables = {}
for attr in attributes:
    print_frequency_table(df, attr)
    print_likelihood_table(df, attr)

    freq_table = pd.crosstab(df[attr], df["Play"])
    total_yes = freq_table["Yes"].sum()
    total_no = freq_table["No"].sum()
    likelihood_tables[attr] = {
        "Yes": {index: row.get("Yes", 0)/total_yes for index, row in freq_table.iterrows()},
        "No":  {index: row.get("No", 0)/total_no for index, row in freq_table.iterrows()}
    }

# --- Ймовірності класів ---
class_probs = df["Play"].value_counts(normalize=True).to_dict()

# --- Функція прогнозу з Laplace smoothing ---
def predict_play_step_by_step(new_day, likelihood_tables, class_probs, attributes, alpha=1):
    print(f"\nPredicting for: {new_day}\n")

    P_yes_components = []
    P_no_components = []

    for attr in attributes:
        val = new_day[attr]
        # Кількість унікальних значень атрибуту
        V = len(likelihood_tables[attr]["Yes"])

        # Отримуємо count для smoothing
        count_yes = likelihood_tables[attr]["Yes"].get(val, 0) * sum(likelihood_tables[attr]["Yes"].values())
        count_no  = likelihood_tables[attr]["No"].get(val, 0) * sum(likelihood_tables[attr]["No"].values())

        total_yes = sum(likelihood_tables[attr]["Yes"].values())
        total_no  = sum(likelihood_tables[attr]["No"].values())

        # Laplace smoothing
        P_attr_yes = (count_yes + alpha) / (total_yes + alpha * V)
        P_attr_no  = (count_no  + alpha) / (total_no  + alpha * V)

        P_yes_components.append(P_attr_yes)
        P_no_components.append(P_attr_no)
        print(f"{attr} = {val} -> P({attr}|Yes) = {P_attr_yes:.4f}, P({attr}|No) = {P_attr_no:.4f}")

    # Добуток ймовірностей
    product_yes = np.prod(P_yes_components)
    product_no  = np.prod(P_no_components)
    print(f"\nProduct of likelihoods: P(Attributes|Yes) = {product_yes:.6f}, P(Attributes|No) = {product_no:.6f}")

    # Множимо на апріорні ймовірності класів
    P_yes_final = product_yes * class_probs.get("Yes", 0)
    P_no_final  = product_no  * class_probs.get("No", 0)
    print(f"P(Yes) * P(Yes prior) = {P_yes_final:.6f}")
    print(f"P(No)  * P(No prior)  = {P_no_final:.6f}")

    # Нормалізація
    total = P_yes_final + P_no_final
    P_yes_norm = P_yes_final / total
    P_no_norm  = P_no_final / total
    print(f"\nNormalized probabilities: P(Yes) = {P_yes_norm:.4f}, P(No) = {P_no_norm:.4f}")

    # Прогноз
    if P_yes_norm > P_no_norm:
        print(f"   Прогноз: Гра відбудеться (Yes) — {P_yes_norm*100:.2f}%")
    else:
        print(f"   Прогноз: Гра не відбудеться (No) — {P_no_norm*100:.2f}%")

    return P_yes_norm, P_no_norm

# --- Прогнози для нових прикладів ---
new_day1 = {"Outlook": "Rain", "Humidity": "High", "Wind": "Weak"}
P_yes1, P_no1 = predict_play_step_by_step(new_day1, likelihood_tables, class_probs, attributes)

new_day2 = {"Outlook": "Overcast", "Humidity": "High", "Wind": "Weak"}
P_yes2, P_no2 = predict_play_step_by_step(new_day2, likelihood_tables, class_probs, attributes)