# -*- coding: utf-8 -*-
"""LR_6_task_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-9HB1XIeYQcnYN2YsgprStM9isi8hZ1i
"""

import pandas as pd
import numpy as np
from pprint import pprint
from IPython.core.display import display, HTML

# 1. Завантаження даних RENFE
url = "https://raw.githubusercontent.com/susanli2016/Machine-Learning-with-Python/master/data/renfe_small.csv"
df = pd.read_csv(url)
df = df[['train_type', 'train_class', 'fare', 'price']].dropna()

# 2. Формування категорії цін
df['PriceCategory'] = pd.qcut(df['price'], q=3, labels=['Low', 'Medium', 'High'])
attributes = ['train_type', 'train_class', 'fare']

# 3. Апріорні ймовірності класів
class_probs = df['PriceCategory'].value_counts(normalize=True).to_dict()
print("\nPrior probabilities (Price categories):")
pprint(class_probs)

# 4. Функція для форматування likelihood таблиць
def create_likelihood_table(df, attr, target):
    freq_table = pd.crosstab(df[attr], df[target])
    totals = freq_table.sum()
    total_all = totals.sum()

    # Додаємо колонку Total
    freq_table['Total'] = freq_table.sum(axis=1)

    # Форматування дробів "число / total"
    for col in freq_table.columns:
        if col != 'Total':
            freq_table[col] = freq_table[col].astype(str) + " / " + totals[col].astype(str)
        else:
            freq_table[col] = freq_table[col].astype(str) + " / " + str(total_all)
    return freq_table

# 5. Генерація likelihood таблиць та збереження для прогнозу
likelihood_tables = {}
for attr in attributes:
    freq_table = pd.crosstab(df[attr], df["PriceCategory"])
    totals = freq_table.sum()

    # Зберігаємо для прогнозу (Laplace smoothing)
    likelihood_tables[attr] = {}
    for category in freq_table.columns:
        likelihood_tables[attr][category] = {
            value: (freq_table.loc[value, category] + 1) / (totals[category] + len(freq_table))
            for value in freq_table.index
        }

# 6. Вивід HTML-таблиць прямо в Colab
for attr in attributes:
    html_table = create_likelihood_table(df, attr, 'PriceCategory').to_html(border=1)
    display(HTML(f"<h3>Likelihood Table for {attr}</h3>"))
    display(HTML(html_table))

# 7. Байєсівський прогноз
def predict_price_category(new_ticket, likelihood_tables, class_probs, attributes):
    print("\nPredicting price category for ticket:")
    pprint(new_ticket)

    scores = {}
    for category in class_probs:
        probs = []
        print(f"\n--- Category: {category} ---")
        for attr in attributes:
            value = new_ticket[attr]
            p = likelihood_tables[attr][category].get(value, 1e-6)  # unseen values
            probs.append(p)
            print(f"P({attr}={value} | {category}) = {p:.6f}")
        score = np.prod(probs) * class_probs[category]
        scores[category] = score
        print(f"Posterior score (unnormalized): {score:.8f}")

    # Нормалізація
    total = sum(scores.values())
    for k in scores:
        scores[k] /= total

    print("\nNormalized posterior probabilities:")
    pprint(scores)

    return max(scores, key=scores.get)

# 8. Приклад прогнозу
new_ticket = {
    'train_type': 'AVE',
    'train_class': 'Turista',
    'fare': 'Promo'
}

result = predict_price_category(new_ticket, likelihood_tables, class_probs, attributes)
print(f"\nPredicted price category: {result}")